#!/bin/sh
echo "export const ENV = { ENABLE_USER_FLAIRS: '$ENABLE_USER_FLAIRS', ENABLE_FEDISEER: '$ENABLE_FEDISEER', DISCORD_URL: '$DISCORD_URL', DONATION_URL: '$DONATION_URL', GIT_REPOSITORY: '$GIT_REPOSITORY', };" > "/app/dist/assets/env.js"
